-- COHORT ANALYSIS/ CUSTOMER RETENTION ANALYSIS ON CUSTOMER LEVEL
WITH CTE1 AS (
SELECT 
    InvoiceNo,
    InvoiceDate,
    CUSTOMERID,
    abs(ROUND(QUANTITY * UNITPRICE, 2)) AS REVENUE
FROM
    sales_retail_ii_cleaned
WHERE
    CustomerID IS NOT NULL
ORDER BY CustomerID
),

CTE2 AS (
SELECT 
        InvoiceNo, 
        CUSTOMERID, 
        INVOICEDATE, 
        DATE_FORMAT(INVOICEDATE, '%Y-%m-01') AS PURCHASE_MONTH,
        DATE_FORMAT(MIN(INVOICEDATE) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE), '%Y-%m-01') AS 
        FIRST_PURCHASE_MONTH,
        REVENUE
    FROM CTE1

),
CTE3 AS (
SELECT 
CUSTOMERID,
FIRST_PURCHASE_MONTH,
concat(
'MONTH_',
PERIOD_DIFF(
EXTRACT(YEAR_MONTH FROM PURCHASE_MONTH),
EXTRACT(YEAR_MONTH FROM FIRST_PURCHASE_MONTH)
)) AS COHORT_MONTH
FROM CTE2
)
SELECT FIRST_PURCHASE_MONTH AS COHORT,
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_0',CUSTOMERID, NULL)) AS 'MONTH_0',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_1',CUSTOMERID, NULL)) AS 'MONTH_1',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_2',CUSTOMERID, NULL)) AS 'MONTH_2',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_3',CUSTOMERID, NULL)) AS 'MONTH_3',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_4',CUSTOMERID, NULL)) AS 'MONTH_4',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_5',CUSTOMERID, NULL)) AS 'MONTH_5',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_6',CUSTOMERID, NULL)) AS 'MONTH_6',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_7',CUSTOMERID, NULL)) AS 'MONTH_7',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_8',CUSTOMERID, NULL)) AS 'MONTH_8',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_9',CUSTOMERID, NULL)) AS 'MONTH_9',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_10',CUSTOMERID, NULL)) AS 'MONTH_10',
COUNT(DISTINCT IF (COHORT_MONTH = 'MONTH_11',CUSTOMERID, NULL)) AS 'MONTH_11'
FROM CTE3
GROUP BY FIRST_PURCHASE_MONTH
ORDER BY FIRST_PURCHASE_MONTH;

-- COHORT ANALYSIS ON REVENUE
WITH CTE1 AS (
SELECT 
    InvoiceNo,
    InvoiceDate,
    CUSTOMERID,
    abs(ROUND(QUANTITY * UNITPRICE, 2)) AS REVENUE
FROM
    sales_retail_ii_cleaned
WHERE
    CustomerID IS NOT NULL
ORDER BY CustomerID
),

CTE2 AS (
SELECT 
        InvoiceNo, 
        CUSTOMERID, 
        INVOICEDATE, 
        DATE_FORMAT(INVOICEDATE, '%Y-%m-01') AS PURCHASE_MONTH,
        DATE_FORMAT(MIN(INVOICEDATE) OVER (PARTITION BY CUSTOMERID ORDER BY INVOICEDATE), '%Y-%m-01') AS 
        FIRST_PURCHASE_MONTH,
        REVENUE
    FROM CTE1

),
CTE3 AS (
SELECT 
CUSTOMERID,
REVENUE,
FIRST_PURCHASE_MONTH AS COHORT,
concat(
'MONTH_',
PERIOD_DIFF(
EXTRACT(YEAR_MONTH FROM PURCHASE_MONTH),
EXTRACT(YEAR_MONTH FROM FIRST_PURCHASE_MONTH)
)) AS COHORT_MONTH
FROM CTE2
)
SELECT COHORT,
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_0',REVENUE, 0)),0) AS 'MONTH_0',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_1',REVENUE, 0)),0) AS 'MONTH_1',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_2',REVENUE, 0)),0) AS 'MONTH_2',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_3',REVENUE, 0)),0) AS 'MONTH_3',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_4',REVENUE, 0)),0) AS 'MONTH_4',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_5',REVENUE, 0)),0) AS 'MONTH_5',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_6',REVENUE, 0)),0) AS 'MONTH_6',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_7',REVENUE, 0)),0) AS 'MONTH_7',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_8',REVENUE, 0)),0) AS 'MONTH_8',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_9',REVENUE, 0)),0) AS 'MONTH_9',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_10',REVENUE, 0)),0) AS 'MONTH_10',
ROUND(SUM(DISTINCT IF (COHORT_MONTH = 'MONTH_11',REVENUE, 0)),0) AS 'MONTH_11'
FROM CTE3
GROUP BY COHORT
ORDER BY COHORT;
